# Konfigurasi untuk extract_outbound.py
# 
# Format konfigurasi:
# [Komentar/Judul konfigurasi]
# Country_ID= [Kode negara, dipisahkan koma jika lebih dari satu]
# Protocol= [Protokol: vless, trojan]
# Security= [Keamanan: tls, ntls]
# Output_Name= [Nama file output]
# Max_Proxies_Per_Provider= [Jumlah maksimal provider yang dipilih untuk negara selain ID (opsional, default: 1)]
#                           [Setiap provider yang dipilih akan memberikan 1 proxy]
#
# Daftar kode negara yang tersedia (diurutkan berdasarkan nama negara):
    # AR (Argentina)       AM (Armenia)         AU (Australia)   
    # AT (Austria)         BE (Belgium)         BR (Brazil)         
    # BG (Bulgaria)        CA (Canada)          CN (China)       
    # CY (Cyprus)          CZ (Czech Republic)  DK (Denmark)       
    # EE (Estonia)         FI (Finland)         FR (France)
    # DE (Germany)         HK (Hong Kong)       HU (Hungary)      
    # IN (India)           ID (Indonesia)       IE (Ireland)        
    # IT (Italy)           JP (Japan)           KZ (Kazakhstan)  
    # KR (South Korea)     LV (Latvia)          LT (Lithuania)     
    # LU (Luxembourg)      MY (Malaysia)        MU (Mauritius)
    # MX (Mexico)          MD (Moldova)         NL (Netherlands) 
    # PH (Philippines)     PL (Poland)          PT (Portugal)       
    # RO (Romania)         RU (Russia)          RS (Serbia)      
    # SG (Singapore)       SK (Slovakia)        ES (Spain)         
    # SE (Sweden)          CH (Switzerland)     TW (Taiwan)
    # TH (Thailand)        TR (Turkey)          UA (Ukraine)      
    # AE (United Arab E)   GB (United Kingdom)  US (United States)  
    # VN (Vietnam)         TF (French Southern Territories)
#
# Daftar protokol yang tersedia:
# vless, trojan
#
# Daftar keamanan yang tersedia:
# tls, ntls

#ID vless tls
Country_ID= ID
Protocol= vless
Security= tls
Output_Name= ID vless tls.json

#ID vless ntls
Country_ID= ID
Protocol= vless
Security= ntls
Output_Name= ID vless ntls.json

#SG vless tls
Country_ID= SG
Protocol= vless
Security= tls
Max_Proxies_Per_Provider= 5
Output_Name= SG vless tls.json

#SG vless ntls
Country_ID= SG
Protocol= vless
Security= ntls
Max_Proxies_Per_Provider= 5
Output_Name= SG vless ntls.json

#ID trojan tls
Country_ID= ID
Protocol= trojan
Security= tls
Output_Name= ID trojan (n)tls.json

#SG trojan tls
Country_ID= SG
Protocol= trojan
Security= tls
Max_Proxies_Per_Provider= 5
Output_Name= SG trojan (n)tls.json

#KR, JP, US vless tls ntls
Country_ID= JP, US, TH
Protocol= vless
Security= tls, ntls
Max_Proxies_Per_Provider= 3
Output_Name= backup.json
