# Konfigurasi untuk extract_outbound.py
# 
# PENGATURAN GLOBAL
# Format yang akan digunakan untuk semua konfigurasi
# Pilihan: bfr, raw, clash, sfa, v2ray
Format= bfr

# Format konfigurasi:
# [Komentar/Judul konfigurasi]
# Country_ID= [Kode negara, dipisahkan koma jika lebih dari satu]
# Protocol= [Protokol: vless, trojan]
# Security= [Keamanan: tls, ntls]
# Output_Name= [Nama file output]
# Max_Proxies_Per_Provider= [Jumlah maksimal provider yang dipilih untuk semua negara (opsional, default: 1)]
#                           [Setiap provider yang dipilih akan memberikan 1 proxy]
#
# Daftar kode negara yang tersedia (diurutkan berdasarkan nama negara):
    # AR (Argentina)       AM (Armenia)         AU (Australia)   
    # AT (Austria)         BE (Belgium)         BR (Brazil)         
    # BG (Bulgaria)        CA (Canada)          CN (China)       
    # CY (Cyprus)          CZ (Czech Republic)  DK (Denmark)       
    # EE (Estonia)         FI (Finland)         FR (France)
    # DE (Germany)         HK (Hong Kong)       HU (Hungary)      
    # IN (India)           ID (Indonesia)       IE (Ireland)        
    # IT (Italy)           JP (Japan)           KZ (Kazakhstan)  
    # KR (South Korea)     LV (Latvia)          LT (Lithuania)     
    # LU (Luxembourg)      MY (Malaysia)        MU (Mauritius)
    # MX (Mexico)          MD (Moldova)         NL (Netherlands) 
    # PH (Philippines)     PL (Poland)          PT (Portugal)       
    # RO (Romania)         RU (Russia)          RS (Serbia)      
    # SG (Singapore)       SK (Slovakia)        ES (Spain)         
    # SE (Sweden)          CH (Switzerland)     TW (Taiwan)
    # TH (Thailand)        TR (Turkey)          UA (Ukraine)      
    # AE (United Arab E)   GB (United Kingdom)  US (United States)  
    # VN (Vietnam)         TF (French Southern Territories)
#
# Daftar protokol yang tersedia: vless, trojan
#
# Daftar keamanan yang tersedia: tls, ntls

#ID vless
#Country_ID= ID
#Protocol= vless
#Security= tls, ntls
#Max_Proxies_Per_Provider= 5
#Output_Name= ID vless

#SG vless
#Country_ID= SG
#Protocol= vless
#Security= tls, ntls
#Max_Proxies_Per_Provider= 4
#Output_Name= SG vless

#TH vless 
#Country_ID= TH
#Protocol= vless
#Security= tls, ntls
#Max_Proxies_Per_Provider= 3
#Output_Name= TH vless 

#MY vless 
#Country_ID= MY
#Protocol= vless
#Security= tls, ntls
#Max_Proxies_Per_Provider= 3
#Output_Name= MY vless

#VN vless 
#Country_ID= VN
#Protocol= vless
#Security= tls, ntls
#Max_Proxies_Per_Provider= 3
#Output_Name= VN vless

#KR, JP, US vless tls ntls
#Country_ID= US, GB, DE, AU, HK
#Protocol= vless
#Security= tls, ntls
#Max_Proxies_Per_Provider= 3
#Output_Name= Backup
