name: Upload Proxy Files to All KV Storage

on:
  workflow_dispatch:

jobs:
  upload-kv-storage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      # exball231
      - name: Upload kvProxyList.json to KV Storage (exball231)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EXBALL231 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EXBALL231 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EXBALL231 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/kvProxyList.json" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/kvProxyList.json"

      - name: Upload proxyList.txt to KV Storage (exball231)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EXBALL231 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EXBALL231 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EXBALL231 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/proxyList.txt" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/proxyList.txt"

      # exball649
      - name: Upload kvProxyList.json to KV Storage (exball649)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EXBALL649 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EXBALL649 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EXBALL649 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/kvProxyList.json" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/kvProxyList.json"

      - name: Upload proxyList.txt to KV Storage (exball649)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EXBALL649 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EXBALL649 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EXBALL649 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/proxyList.txt" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/proxyList.txt"

      # exball689
      - name: Upload kvProxyList.json to KV Storage (exball689)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EXBALL689 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EXBALL689 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EXBALL689 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/kvProxyList.json" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/kvProxyList.json"

      - name: Upload proxyList.txt to KV Storage (exball689)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EXBALL689 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EXBALL689 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EXBALL689 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/proxyList.txt" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/proxyList.txt"

      # ex_ball27389
      - name: Upload kvProxyList.json to KV Storage (ex_ball27389)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EX_BALL27389 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EX_BALL27389 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EX_BALL27389 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/kvProxyList.json" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/kvProxyList.json"
            
      - name: Upload proxyList.txt to KV Storage (ex_ball27389)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN_EX_BALL27389 }}
          KV_STORAGE_ID: ${{ secrets.KV_ID_EX_BALL27389 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_EX_BALL27389 }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/storage/kv/namespaces/$KV_STORAGE_ID/values/proxyList.txt" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --data-binary "@proxy-scaner/proxyList.txt"
